run:
  tests: true

linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - gofumpt
    - gci
    - errcheck
    - revive
    - gocritic
    - testifylint
