run:
  tests: true

linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - gofumpt
    - gci
    - testifylint

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
