version: "2"

run:
  tests: true
  timeout: 5m

linters:
  # Enable specific linters
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - misspell
    - testifylint
    - thelper
    - copyloopvar # Detect copy loops
    - errcheck # Detect unchecked errors
    - govet # Reports suspicious constructs
    - ineffassign # Detect unused assignments
    - staticcheck # Go static analysis
    - unused # Detect unused constants, variables, functions and types

    # Additional recommended linters
    - gocritic # A more opinionated linter
    - gosec # Security checker
    - misspell # Find commonly misspelled words
    - bodyclose # Check HTTP response bodies are closed
    - goconst # Find repeated strings that could be constants
    - gocognit # Check cognitive complexity
    - whitespace # Check trailing whitespace
    - thelper # Detect test helpers not using t.Helper()
    - tparallel # Detect incorrect usage of t.Parallel()

  # enable lager because changes are huge
    # - revive

  settings:
    gocritic:
      enable-all: true
      disabled-checks:
        - dupSubExpr
        - dupImport



  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      # Section configuration to compare against.
      # Section names are case-insensitive and may contain parameters in ().
      # The default order of sections is `standard > default > custom > blank > dot > alias > localmodule`,
      # If `custom-order` is `true`, it follows the order of `sections` option.
      # Default: ["standard", "default"]
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/cosmos/cosmos-sdk) # Custom section: groups all imports with the specified Prefix.
        - prefix(github.com/cosmos/ibc-go)
        - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
        - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
        - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
        - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
      # Enable custom order of sections.
      # If `true`, make the section order the same as the order of `sections`.
      # Default: false
      custom-order: true
      # Drops lexical ordering for custom sections.
      # Default: false
      no-lex-order: true
  exclusions:
    # Skip generated files.
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
