

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureFree(
				UniffiForeignFutureFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureStructU8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureStructU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureStructI8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureStructI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureStructU16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureStructU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureStructI16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureStructI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureStructU32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureStructU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureStructI32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureStructI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureStructU64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureStructU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureStructI64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureStructI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureStructF32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureStructF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureStructF64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureStructF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void* returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t callback_data, UniffiForeignFutureStructPointer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompletePointer(
				UniffiForeignFutureCompletePointer cb, uint64_t callback_data, UniffiForeignFutureStructPointer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureStructRustBuffer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureStructRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureStructVoid result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureStructVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WASMVM_FN_FUNC_VERSION_STR
#define UNIFFI_FFIDEF_UNIFFI_WASMVM_FN_FUNC_VERSION_STR
RustBuffer uniffi_wasmvm_fn_func_version_str(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_WASMVM_RUSTBUFFER_ALLOC
RustBuffer ffi_wasmvm_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_WASMVM_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_wasmvm_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_WASMVM_RUSTBUFFER_FREE
void ffi_wasmvm_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_WASMVM_RUSTBUFFER_RESERVE
RustBuffer ffi_wasmvm_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_U8
void ffi_wasmvm_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_U8
void ffi_wasmvm_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_U8
void ffi_wasmvm_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_wasmvm_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_I8
void ffi_wasmvm_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_I8
void ffi_wasmvm_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_I8
void ffi_wasmvm_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_I8
int8_t ffi_wasmvm_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_U16
void ffi_wasmvm_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_U16
void ffi_wasmvm_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_U16
void ffi_wasmvm_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_wasmvm_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_I16
void ffi_wasmvm_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_I16
void ffi_wasmvm_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_I16
void ffi_wasmvm_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_I16
int16_t ffi_wasmvm_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_U32
void ffi_wasmvm_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_U32
void ffi_wasmvm_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_U32
void ffi_wasmvm_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_wasmvm_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_I32
void ffi_wasmvm_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_I32
void ffi_wasmvm_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_I32
void ffi_wasmvm_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_I32
int32_t ffi_wasmvm_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_U64
void ffi_wasmvm_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_U64
void ffi_wasmvm_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_U64
void ffi_wasmvm_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_wasmvm_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_I64
void ffi_wasmvm_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_I64
void ffi_wasmvm_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_I64
void ffi_wasmvm_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_I64
int64_t ffi_wasmvm_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_F32
void ffi_wasmvm_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_F32
void ffi_wasmvm_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_F32
void ffi_wasmvm_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_F32
float ffi_wasmvm_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_F64
void ffi_wasmvm_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_F64
void ffi_wasmvm_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_F64
void ffi_wasmvm_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_F64
double ffi_wasmvm_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_POINTER
void ffi_wasmvm_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_POINTER
void ffi_wasmvm_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_POINTER
void ffi_wasmvm_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_POINTER
void* ffi_wasmvm_rust_future_complete_pointer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_wasmvm_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_wasmvm_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_wasmvm_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_wasmvm_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_POLL_VOID
void ffi_wasmvm_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_CANCEL_VOID
void ffi_wasmvm_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_FREE_VOID
void ffi_wasmvm_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_WASMVM_RUST_FUTURE_COMPLETE_VOID
void ffi_wasmvm_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WASMVM_CHECKSUM_FUNC_VERSION_STR
#define UNIFFI_FFIDEF_UNIFFI_WASMVM_CHECKSUM_FUNC_VERSION_STR
uint16_t uniffi_wasmvm_checksum_func_version_str(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WASMVM_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_WASMVM_UNIFFI_CONTRACT_VERSION
uint32_t ffi_wasmvm_uniffi_contract_version(void
    
);
#endif

