use cosmwasm::traits::{ReadonlyStorage, Storage};

use crate::error::GoResult;
use crate::memory::Buffer;

// this represents something passed in from the caller side of FFI
#[repr(C)]
pub struct db_t {
    _private: [u8; 0],
}

// These functions should return GoResult but because we don't trust them here, we treat the return value as i32
// These functions should return GoResult but because we don't trust them here, we treat the return value as i32
// and then check it when converting to GoResult manually
#[repr(C)]
pub struct DB_vtable {
    pub read_db: extern "C" fn(*mut db_t, Buffer, *mut Buffer) -> i32,
    pub write_db: extern "C" fn(*mut db_t, Buffer, Buffer) -> i32,
}

#[repr(C)]
pub struct DB {
    pub state: *mut db_t,
    pub vtable: DB_vtable,
}

impl ReadonlyStorage for DB {
    fn get(&self, key: &[u8]) -> Option<Vec<u8>> {
        let key = Buffer::from_vec(key.to_vec());
        let mut result_buf = Buffer::default();
        let go_result: GoResult =
            (self.vtable.read_db)(self.state, key, &mut result_buf as *mut Buffer).into();
        let key = unsafe { key.consume() };
        match go_result {
            GoResult::Ok => { /* continue */ }
            _ => {
                // TODO handle this better. in
                panic!("Go panicked while reading key {:?}", key);
            }
        }

        if result_buf.ptr.is_null() {
            return None;
        }

        // We initialize `result_buf` with a null pointer. if it is not null,
        // that means it was initialized by the go code, with values generated by `memory::allocate_rust`
        unsafe { Some(result_buf.consume()) }
    }
}

impl Storage for DB {
    fn set(&mut self, key: &[u8], value: &[u8]) {
        let key = Buffer::from_vec(key.to_vec());
        let value = Buffer::from_vec(value.to_vec());
        // caller will free input
        let go_result: GoResult = (self.vtable.write_db)(self.state, key, value).into();
        let key = unsafe { key.consume() };
        let _value = unsafe { value.consume() };
        match go_result {
            GoResult::Ok => { /* continue */ }
            _ => {
                // TODO handle this better. in
                panic!("Go panicked while writing key {:?}", key);
            }
        }
    }
}
