/* (c) 2019 Confio UO. Licensed under Apache-2.0 */

/* Generated with cbindgen:0.9.1 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Buffer {
  uint8_t *ptr;
  uintptr_t size;
} Buffer;

typedef struct db_t {

} db_t;

typedef struct DB {
  db_t *state;
  int64_t (*c_get)(db_t*, Buffer, Buffer);
  void (*c_set)(db_t*, Buffer, Buffer);
} DB;

int32_t add(int32_t a, int32_t b);

/**
 * divide returns the rounded (i32) result, returns a C error if div == 0
 */
int32_t divide(int32_t num, int32_t div);

void free_rust(Buffer buf);

Buffer get_last_error(void);

Buffer greet(Buffer name);

Buffer may_panic(int32_t guess);

void update_db(DB db, Buffer key);
