name: Cargo Deny

on:
  push:
    branches: [main]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/deny.toml"
      - ".github/workflows/cargo-deny.yml"
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/deny.toml"
      - ".github/workflows/cargo-deny.yml"

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
      #    - advisories  - this should be restored at some point
          - bans
          - sources
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.checks }}
          arguments: --all-features --exclude-dev
          rust-version: stable
          manifest-path: libwasmvm/Cargo.toml
