name: Go Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.12'
          cache: false

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@v0.4.0

      - name: Install shfmt
        run: GO111MODULE=on go install mvdan.cc/sh/v3/cmd/shfmt@v3.7.0

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Check Go formatting with gofmt
        run: |
          [ "$(gofmt -l .)" = "" ] || (gofmt -d . && exit 1)

      - name: Check Go formatting with gofumpt
        run: |
          [ "$(gofumpt -l .)" = "" ] || (gofumpt -d . && exit 1)

      - name: Check go mod tidy
        run: |
          go mod tidy
          git diff --exit-code

      - name: Run shfmt
        run: shfmt --diff .

      - name: Run shellcheck
        run: find . -name "*.sh" -exec shellcheck {} +

      - name: Build Go project
        run: make build-go

      - name: Go integration tests
        run: make test

      - name: Go safety tests
        run: make test-safety
