name: Go Build and Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: false

      - name: Check go mod tidy
        run: |
          go mod tidy
          git diff --exit-code

      - name: Build Go project
        run: make build-go

      - name: Go integration tests
        run: make test

      - name: Go wazero tests
        run: go test -tags wazero ./...

      - name: Go safety tests
        run: make test-safety
